spring.application.name=product-api

# src/main/resources/application.properties

# Port de l'application
server.port=8086

# Base de données
# "mysql" sera le nom du conteneur Docker (pour le déploiement)
# Pour tests locaux, remplacez "mysql" par "localhost"
spring.datasource.url=jdbc:mysql://localhost:3306/product_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true